name: movieguide
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.2
  get: 4.1.4
  google_fonts: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  path: ^1.8.0
  provider: ^5.0.0
  retrofit: ^2.0.0
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  retrofit_generator: ^2.0.0

dependency_overrides:
  retrofit_generator:
    # https://github.com/trevorwang/retrofit.dart/issues/300
    git:
      url: git@github.com:Chimerapps/retrofit.dart.git
      ref: 9f90296751984b359937c38563da5b19db5550f5
      path: generator

flutter:
  uses-material-design: true
